#Test
name: My CICD Workflow

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [14.20.0]


    steps:
      - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v3
        # with:
        #   node-version: ${{ matrix.node-version }}
        #   cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
        

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "running..........."
        
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: ['build', 'test']
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Docker build
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Login to GitHub Packages
        uses: docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}
        
      - name: Build an image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ./
          tags: |
            anurodh1/gitops:latest
            ghcr.io/anurodhacharya/gitops:latest
          
          push: ${{ github.ref == 'refs/heads/master' }}
        
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
